### ISSUE TITLE
过渡阶段能不能通过网页cookie获取api数据

### ISSUE THREAD

**Issue by ekibun** [bangumi/server#10]
客户端里是解析网页的，在功能没有完全覆盖之前客户端需要存两套登录信息非常麻烦，如果可以那就太方便了

**Comment by Trim21** [comment]
只读api不需要认证

**Comment by ekibun** [comment]
当然是说用户信息，或者现在已有的api能开放cookie访问也很方便，可以只包含只读的api

**Comment by ekibun** [comment]
或者反过来，api auth能读取网页内容（bgm38）

**Comment by Trim21** [comment]
sai老板给否了
