### ISSUE TITLE
关于获取用户收藏 API 的 limit 参数设计

### ISSUE THREAD

**Issue by KiritaniAyaka** [bangumi/server#126]
### 现状

获取用户收藏的 [`GET /v0/users/{username}/collections`](https://bangumi.github.io/api/#/%E6%94%B6%E8%97%8F/get_user_collection_v0_users__username__collections_get) 其中 limit 参数接收最大值 100，默认值 30。

当 limit 参数大于 **用户总收藏数** 时会 Bad Request，产生了无意义的失败请求，徒增 API 使用难度，也为服务器增大了压力。

```json
{
    "title": "Bad Request",
    "details": {
        "error": "limit should less equal than 40",
        "path": "/v0/users/{username}/collections",
        "query_string": "limit=50&offset=0"
    },
    "description": "limit should less equal than 40"
}
```

### 建议

1. 新增一个获取用户收藏数的 API，开发者自行避免使用大于总数的 limit 参数进行请求。
2. 修改逻辑。当 limit 大于用户总收藏数时，返回尽可能多的收藏条目数。

### 临时方案

个人认为当前可行的解决方案，采用一个小于 100 的 limit 参数进行请求，如果出现 Bad Request，从信息中拿到 limit 允许的最大值（即上面 `description` 中的数字），并进行第二次请求。

**Comment by Trim21** [comment]
看起来像是检查offset的时候不小心比较了limit...

**Comment by KiritaniAyaka** [comment]
> 看起来像是检查offset的时候不小心比较了limit...

大佬太快了，还以为在 GitHub 上联系会不怎么及时打算去小组里发个主题的，结果主题还没发出去 GitHub 这边已经有回复了 23333。

**Comment by Trim21** [comment]
github上提issue有邮件的，在小组发帖才可能联系不及时

**Comment by KiritaniAyaka** [comment]
> github上提issue有邮件的，在小组发帖才可能联系不及时

大佬不要急（）
现在能用了不过报错信息错了
offset 大于收藏总数的时候报错：
`limit should less equal than 40`
应该是
`offset should less equal than 40`

另外想问一下用什么邮件客户端能这么及时233，咱用 QQ 邮箱多账号管理有 bug 。

**Comment by Trim21** [comment]
就是QQ邮箱在QQ客户端的提醒

**Comment by Trim21** [comment]
（其实还有slack频道里的github bot

**Comment by KiritaniAyaka** [comment]
> （其实还有slack频道里的github bot

彳亍，咱去康康（
