### ISSUE TITLE
[Feature Request]: 对于书籍类条目建立系列与单行本的关系

### ISSUE THREAD

**Issue by EverettSummer** [bangumi/server#145]
**你想添加的新功能**
以这个漫画系列为例 https://bgm.tv/subject/135218 该条目为 漫画 系列 其下有若干个单行本条目
**你希望的解决方案**
可为subject增加一个property: isSet （或者isSeries, isCollection）
对于系列类subject，增加一个API，查找其所有的单行本的subject
**其他可能的替代方案**
暂未找到其他API可以替代, 从数据库角度可以找关联条目只有该系列条目的条目，但API似乎没找到反过来查的
**其他相关信息**

**Comment by Trim21** [comment]
你会写go的话可以PR一下

**Comment by Trim21** [comment]
一个方向的关联名是”单行本“，反向关联是”系列“
