### ISSUE TITLE
[Feature Request]: get /v0/persons/{person_id}/characters 与/v0/characters/{character_id}/persons 是否考虑增加关系字段

### ISSUE THREAD

**Issue by EverettSummer** [bangumi/server#151]
**你想添加的新功能**

网页上，角色的出演列表，以及人物的角色列表，均包含了作品中，角色的类别：按照源码看，有三个类别：
1: 主角
2: 配角
3: 客串
这个字段目前只能从/v0/subjects/{subject_id}/characters或者characters/{character_id}/subjects结果获得。
那么实现网页上的效果，就要请求两次

**你希望的解决方案**

在上述API中加入staff字段

**其他可能的替代方案**

GraphQL（长远考虑

**其他相关信息**

**Comment by Trim21** [comment]
要是有人愿意PR的话

Everett Summer ***@***.***> 于2022年5月6日周五 22:20写道：

**Comment by EverettSummer** [comment]
Go苦手

**Comment by Iwakura-Reinn** [comment]
我来尝试添加一下吧
