### ISSUE TITLE
[Feature Request]: 时间胶囊

### ISSUE THREAD

**Issue by trim21** [bangumi/server#176]
稍微做了一点，把现在的各种时间线type和对应的类型整理出来了 https://github.com/bangumi/server/compare/master...feature/timeline

**Comment by Trim21** [comment]
@TWT233 可以做这个（）

**Comment by TWT233** [comment]
狠啊老板 有没有详细点的描述

**Comment by TWT233** [comment]
ok, 接口 route 有没有定？我看现在的变更里还没有

**Comment by Trim21** [comment]
暂无。现在是想做进度管理，然后需要支持在修改进度的时候生成一条进度的时间线

**Comment by Trim21** [comment]
所以http api到也不太要紧。

**Comment by TWT233** [comment]
好

**Comment by TWT233** [comment]
我看看欸 重装了电脑 还在配环境

**Comment by TWT233** [comment]
我觉得现在只写 get by id/uid 就好

**Comment by Trim21** [comment]
只需要写创建的方法，都不需要写get的方法（

**Comment by TWT233** [comment]
对 忘了这个 那我一起写了好了

**Comment by TWT233** [comment]
这里有数据的scheme或者老代码参考吗

**Comment by Trim21** [comment]
https://gist.github.com/Trim21/b930f98e000c7024b41de74f92d192aa

**Comment by TWT233** [comment]
ACK
