### ISSUE TITLE
[Feature Request]: 小组概览接口

### ISSUE THREAD

**Issue by Ayase-252** [bangumi/server#182]
**你想添加的新功能**

私有小组概览接口

**你希望的解决方案**
新增接口

GET `/p/group/${name}`

期望返回:

| 字段 | 类型 | 意义 |
|---|---|---|
| `title` | `string` | 小组名称 |
| `created_at` | `string` | 创建时间，格式 `YYYY-MM-DD HH:mm` |
| `description`| `string` | 小组介绍 |
| `total_members` | `number` | 小组成员数量 |
| `new_members` | `User[]` | 最近加入的小组成员，最多 10 个 |
| `related_groups` | `Group[]` | 成员喜欢去的小组，最多 6 个 |
| `new_topics` | `Topic[]`  | 最新讨论，最多 10 个 |

**其他可能的替代方案**

**其他相关信息**

![Screen Shot 2022-06-21 at 23 38 43](https://user-images.githubusercontent.com/6264033/174842829-1f51fe37-b412-4809-a299-5b0dee1121c1.png)

**Comment by Trim21** [comment]
这个创建时间返回时间戳吧，前端自己格式化

**Comment by Trim21** [comment]
`name`有些歧义吧，图里这个`name`改叫`title`好了

**Comment by Trim21** [comment]
讨论贴这个字段先等那个PR合了，不然就成重复工作了。

**Comment by Trim21** [comment]
`related_groups` 这个暂时先摸了，前端先留空吧（
