### ISSUE TITLE
[Bug]: 分页超出边界

### ISSUE THREAD

**Issue by FoundTheWOUT** [bangumi/server#248]
现在分页超出边界返回的是200的空数据
#### 你想添加的新功能
返回一个404，或者200里带有错误信息

<img width="950" alt="image" src="https://user-images.githubusercontent.com/47922588/201355154-a186901f-0abf-4ce8-b51e-ba75a6804f88.png">

**Comment by trim21** [comment]
哪个API啊

**Comment by FoundTheWOUT** [comment]
`/p/groups/{name}/topics`，分页逻辑不是公用的吗，可能每个带分页功能的api都有这个问题

**Comment by trim21** [comment]
超出边界现在应该是 Bad Request

**Comment by trim21** [comment]
可能这几个路由给漏掉了。等有空再修一下
