### ISSUE TITLE
[BUG]: wrong timeline

### ISSUE THREAD

**Issue by trim21** [bangumi/server#265]
**描述**

简短的表述你遇到的问题

**如何重现**

收藏 https://bgm.tv/subject/354667

然后 

```python
r = requests.patch("https://api.bgm.tv/v0/users/-/collections/354667", json={
    "ep_status": 6,
    "tags": ["string", "开放世界"]
}, headers={...})
```

**预期**

![image](https://user-images.githubusercontent.com/13553903/209008778-0f53bdb7-b84e-4517-ab89-3ed1e30dbde4.png)

**实际行为**

![image](https://user-images.githubusercontent.com/13553903/209008605-85ac4021-271b-4369-b294-23f54e86ab2b.png)

@TWT233 

带进度的时间线是这样的 

```json
{
  "eps_total": "5",
  "eps_update": 4,
  "subject_id": "354667",
  "subject_name": "沙盒",
  "subject_type_id": "1",
  "vols_total": "??",
  "vols_update": null
}
```

现在生成的时间线只是简单地标记了收藏状态。

时间胶囊相关的微服务在 https://github.com/bangumi/service-timeline

**Comment by 2247407869** [comment]
请问一下我应该如何启动一个像图片里那样的前端测试界面。前端项目拉下来跑起来好像只有一个登录功能 @trim21

**Comment by trim21** [comment]
> 请问一下我应该如何启动一个像图片里那样的前端测试界面。前端项目拉下来跑起来好像只有一个登录功能 @trim21

这个issue里的图片是从bgm.tv截的
