### ISSUE TITLE
[Feature Request]: 获取条目的ISBN/IMDB信息

### ISSUE THREAD

**Issue by alphatownsman** [bangumi/server#278]
**你想添加的新功能**
获取条目的ISBN/IMDB信息 

**你希望的解决方案**
根据 https://github.com/bangumi/dev-docs/blob/master/%E6%9D%A1%E7%9B%AE.md ，条目似乎是有IMDB/ISBN信息，希望能在 [getSubjectById endpoint](https://bangumi.github.io/api/#/%E6%9D%A1%E7%9B%AE/getSubjectById) 返回 uid 这个字段

**其他可能的替代方案**
用一个uid返回多个来源的第三方ID有点hacky，如果有完善的id类型信息更好，当然并非必须

**其他相关信息**
related with #37 

起因：部分[NeoDB](https://mastodon.social/@neodb)的用户希望能添加bangumi的条目到自己的标记库，但同时希望避免创建重复的条目，如果有第三方ID比如ISBN/IMDB(以及steam id、album upc，如果有的话)希望能在API中酌情添加。

谢谢考虑。🙏🏻

**Comment by trim21** [comment]
可以考虑从wiki信息里面提取

**Comment by alphatownsman** [comment]
> 从wiki信息里面提取

是指解析 https://bangumi.tv/subject/415472 这类url的页面内容吗

**Comment by trim21** [comment]
> > 从wiki信息里面提取
> 
> 是指解析 https://bangumi.tv/subject/415472 这类url的页面内容吗

```json
{
  "date": "1998-09-25",
  "platform": "小说",
...
  "name": "第一次的親密接觸",
  "name_cn": "第一次的亲密接触",
  "tags": [
   ...
  ],
  "infobox": [
...
    {
      "key": "ISBN",
      "value": "9577086705"
    },
...
  ],
...
  "id": 1,
  "eps": 0,
  "volumes": 0,
  "locked": false,
  "nsfw": false,
  "type": 1
}
```

**Comment by alphatownsman** [comment]
Thanks!
