### ISSUE TITLE
人物编辑历史

### ISSUE THREAD

**Issue by Trim21** [bangumi/server#28]
应该是有入库，但目前的前端没有查看方法

在这个表中 https://github.com/bangumi/dev-env/blob/main/sql/schema/chii_rev_history.sql

各种 type 的定义在这个php文件中 https://gist.github.com/Trim21/2f12d92b04ee65dcd9026ffdb1bfb800

**Comment by Trim21** [comment]
这个blob字段存的是PHP序列化+gzip压缩之后的结果。在python中处理可以参考 https://github.com/bangumi/server/commit/8adf53753d85a57cf55d22810c399b43694001d8

**Comment by MichaelMai2000** [comment]
我想做这个功能。

我目前的理解是：
- 参考已有的 API
  - 如 https://github.com/bangumi/server/blob/master/pol/api/v0/person.py
- 设计字段
  
    - [ ] `/persons/{person_id}/histories` 返回所有 `rev_id` 的列表。
    `/persons/{person_id}/history/{rev_id}` 返回一个完成的 `person`，与 `get_person()` 返回一致。

    - [ ] 或者，如果不同类别的 history 用 `rev_id` 足够区分（存疑），
    `/history/{rev_id}` 返回一个完成的 `history` 。

**Comment by Trim21** [comment]
第一种吧
