### ISSUE TITLE
条目图片api

### ISSUE THREAD

**Issue by ekibun** [bangumi/server#31]
能不能有一个api能302到指定subject的图片，比如
`/api/subject/xxx/image?type=large`
在某些只有标题id没有其他信息的地方能用上
角色和人物同理

**Comment by Trim21** [comment]
我感觉可以，甚至可以直接返回对应图片内容。

**Comment by Sai** [comment]
图片走 CDN 的，直接返回 CDN 就废了，然后还要考虑之后 subject api nsfw 加鉴权的问题。

**Comment by Trim21** [comment]
那还是302吧

**Comment by ekibun** [comment]
终于想到用例了
在显示吐槽的时候有根据uid拿图片的需求
希望一并做了
