### ISSUE TITLE
[Feature Request]:  增加 Subject 到用户收藏

### ISSUE THREAD

**Issue by RanKKI** [bangumi/server#324]
**你想添加的新功能**

增加某 Subject 到用户收藏，例如用户对一新 Subject，将其设置为「在看」状态 

目前只有 PATCH 方法用做修改，但如果不存在，会报错

https://github.com/bangumi/server/blob/f9d97244a1238e0b5911538c43f40d8a3085ccaf/web/handler/user/patch_subject_collection.go#L84-L87

**你希望的解决方案**

增加 POST 请求

**其他可能的替代方案**

**其他相关信息**

kookxiang/jellyfin-plugin-bangumi#61

**Comment by trim21** [comment]
pr一下（

**Comment by RanKKI** [comment]
> pr一下（

但我在想， 如果 patch 的不存在是报错，还是新建

**Comment by trim21** [comment]
加个put

**Comment by trim21** [comment]
先打开了，等部属了再关
