### ISSUE TITLE
API 422 Response缺少 Access-Control-Allow-Origin Header

### ISSUE THREAD

**Issue by markni** [bangumi/server#33]
和 https://github.com/bangumi/api/issues/70 ~~相同的问题，sai只修改了老API。~~  

如果API返回422,响应缺少 Access-Control-Allow-Origin header

![image](https://user-images.githubusercontent.com/1743179/146692161-310d1d50-d54a-4c65-abac-eb0055d95533.png)

重现方法：

1. 打开https://bangumi.github.io/api/
2. 选择第一个API /v0/persons
3. 点击Try it out
4. 不做任何选项，直接点 Execute
5. 查看console

**Comment by Trim21** [comment]
@Sai

**Comment by Trim21** [comment]
我记得新api sai老板也改了

**Comment by Trim21** [comment]
![Screenshot_2021-12-20-06-09-36-189_com brave browser](https://user-images.githubusercontent.com/13553903/146692562-b94f8aa6-4e3d-4a5c-8838-ee38f1ce326c.jpg)

这不是可以吗

**Comment by Trim21** [comment]
看你请求的UR queryL好像不太对，应该是Nginx的add header少了 always选项

**Comment by markni** [comment]
确实，看来是422响应会有这个问题

**Comment by Trim21** [comment]
这个生成的openapi好像也有点问题，默认的参数居然请求失败
