### ISSUE TITLE
新增单个用户收藏[POST]/v0/users/-/collections/{subject_id} 似乎不能正常工作

### ISSUE THREAD

**Issue by ascrazy0** [bangumi/server#350]
```
data = {
    "status": 3,
    "private": False,
}
awa = requests.post(
    f"https://api.bgm.tv/v0/users/-/collections/363308", headers=headers, json=data)
print(awa.status_code)
```
状态码：202
试了别的剧集也似乎依旧存在这样的问题

**Comment by trim21** [comment]
cc @RanKKI

**Comment by RanKKI** [comment]
```golang
    if s.TypeID != model.SubjectTypeBook {
            if r.VolStatus.Set || r.EpStatus.Set {
                    return res.BadRequest("can't set 'vol_status' or 'ep_status' on non-book subject")
            }
    }
```

@trim21 

这里是为啥这么设计? 之前有啥诡异的 bug 么

**Comment by trim21** [comment]
> ```go
>     if s.TypeID != model.SubjectTypeBook {
>             if r.VolStatus.Set || r.EpStatus.Set {
>                     return res.BadRequest("can't set 'vol_status' or 'ep_status' on non-book subject")
>             }
>     }
> ```
> 
> @trim21
> 
> 这里是为啥这么设计? 之前有啥诡异的 bug 么

对于从 13 集开始的第二季条目来说会有造成歧义。，比如EpStatus设置为2/14可能有不同的理解。

**Comment by trim21** [comment]
还有比如有0.5的的条目，比如 1 1.5 2 3，如果用户设置了EpStatus=3的时候要不要修改1.5章节的状态

**Comment by RanKKI** [comment]
@ascrazy0 `status` 不是个合法字段，如果要改某条目的状态要用 `type`

```
1 // 想看
2 // 看过
3 // 在看
4 // 搁置
5 // 抛弃
```

**Comment by trim21** [comment]
所以不是bug，是请求错了吗？

**Comment by trim21** [comment]
> @ascrazy0 `status` 不是个合法字段，如果要改某条目的状态要用 `type`
> 
> ```
> 1 // 想看
> 2 // 看过
> 3 // 在看
> 4 // 搁置
> 5 // 抛弃
> ```

好像可以设置`DisallowUnknownFields`禁用不认识的字段

**Comment by RanKKI** [comment]
> 所以不是bug，是请求错了吗？

应该是这样的，但不确定 op 具体的问题是不是和条目状态有关。

（不过 type 这个字段名的确有点迷惑 🤥

**Comment by trim21** [comment]
现在会返回400错误，提示`status`字段不存在了
