### ISSUE TITLE
[GET] /v0/users/-/collections/{subject_id}/episodes 章节收藏信息 Bad Request

### ISSUE THREAD

**Issue by czy0729** [bangumi/server#447]
![image](https://github.com/bangumi/api/assets/13514316/4d27c50e-348b-4410-9d6f-49842e775fdb)
![image](https://github.com/bangumi/api/assets/13514316/2f4d18fd-ae92-48c1-baf8-b26e1efa024a)

description: "\"214272/episodes\" is not valid ID"
似乎是路由就匹配错误了

**Comment by trim21** [comment]
似乎是路由冲突了，`${id}/episodes` 匹配到 `${id}` 上面去了

**Comment by trim21** [comment]
你用错了，没有你试图调用的这个API... 这个 API 只能以 `-` 作为用户名，查询当前用户的收藏

https://bangumi.github.io/api/#/%E6%94%B6%E8%97%8F

**Comment by czy0729** [comment]
这么怪的用法，确实可以。

**Comment by trim21** [comment]
支持任意用户名的话还要涉及到鉴权，私有收藏等等东西，而且这API也没必要支持第三人查询，就这么设计了。
