### ISSUE TITLE
[BUG]: /v0/indices/index_id/subjects返回的数据错误

### ISSUE THREAD

**Issue by track23** [bangumi/server#477]
https://api.bgm.tv/v0/indices/52526/subjects
对应这个页面 https://bgm.tv/index/52526

当目录中有收藏角色时，返回的数据是错的。

**Comment by track23** [comment]
原来已经有人提过了。#247
角色可以加入目录但接口不支持，那么能增加一个查询已收藏角色列表的接口吗（目前只有查询单个角色的接口）。收藏不能排序，有总比没有好。

**Comment by trim21** [comment]
已修复

**Comment by track23** [comment]
原来是直接不显示角色啊。那只能各显神通。

**Comment by trim21** [comment]
我没时间写，而且没人PR。

你可以PR一个
