### ISSUE TITLE
获取编辑历史API设计

### ISSUE THREAD

**Issue by Trim21** [bangumi/server#51]
编辑历史API拥有一个公用前缀 `/v0/revisions/`, 按照不同的编辑种类分成不同的子路由

- 列出某个条目所有的修订 `/v0/revsions/subjects?subject_id=$value`
- 条目编辑历史 `/v0/revsions/subjects/{rev_id}`

其他wiki类型如人物/角色/章节类似。

**Comment by Jarvie8176** [comment]
建议把revision放到对应编辑种类的下面？比如`/v0/subjects/:id/revisions`

revision本身依附于具体条目存在，一对多，而且不同类型对应的处理逻辑可能也有一定程度的区别

**Comment by Trim21** [comment]
我一开始也是这么想的，然后遇到了章节支持批量编辑的问题。

**Comment by Jarvie8176** [comment]
> 我一开始也是这么想的，然后遇到了章节支持批量编辑的问题。

批量编辑可以走单独的endpoint，简单包装一下然后共用一套crud逻辑

> `/v0/episodes/:id/revisions` 就会非常歧义，非`:id`的章节修改还要不要一起返回了。

没太看懂，是指有的章节可以没有id吗(bgm38)

**Comment by Trim21** [comment]
> 批量编辑可以走单独的endpoint，简单包装一下然后共用一套crud逻辑

主要是说暴露出来的API，不是具体的实现。


> 没太看懂，是指有的章节可以没有id吗(bgm38)

/v0/episodes/:id/revisions/:rev_id 可能包含非当前episode_id的修改

**Comment by Jarvie8176** [comment]
> /v0/episodes/:id/revisions/:rev_id 可能包含非当前episode_id的修改

原来我没有wiki权限(bgm38)。有没有具体的例子？

---

`rev_id`是全局还是依附于具体条目吗？比如 `v0/episodes/:id/revisions/1` vs. `v0/episodes/:id/revisions/{uuid}`

前者可以先添加assign unique id，后者不用处理

可以提供这几个endpoint:

`GET /v0/episodes/:id/revisions` 列出ep的全部修订历史
`POST /v0/episodes/:id/revisions` 创建新修订
`GET /revisions/:id` 获取修订记录细节
`PATCH /revisions/:id` 修改某条修订记录 (?)
`PATCH /revisions/ep?ids={id_0},{id_1}` 批量修改ep的修订记录

**Comment by Trim21** [comment]
rev id是全局的，所以我才建议这样处理路由

**Comment by Trim21** [comment]
![image](https://user-images.githubusercontent.com/13553903/147393278-619ef82e-f715-4368-b946-b67df40ad97e.png)

**Comment by Trim21** [comment]
具体put和post的api后面再说
