### ISSUE TITLE
[BUG]: 修改收藏条目的评分无效

### ISSUE THREAD

**Issue by BTMuli** [bangumi/server#530]
**描述**

调用开放 API 的 [修改用户单个收藏](https://bangumi.github.io/api/#/%E6%94%B6%E8%97%8F/patchUserCollection)，数据为 `{rate: 9}`（示例），请求之后返回 204 状态码，但是调用 [获取用户单个收藏](https://bangumi.github.io/api/#/%E6%94%B6%E8%97%8F/getUserCollection) 后结果并未刷新。

另：在 `bangumi.tv` 网页端点击评分后，调用会实时刷新结果。
再另：哪怕多次请求修改评分，尽管返回的都是 `204` 但是没有一次结果刷新的。

**如何重现**

1. 调用API修改已收藏条目的评分
2. 调用API获取已收藏条目信息

**预期**

修改评分后实时刷新返回结果

**实际行为**

修改评分后返回 `204` 但是结果并未刷新

**额外信息**

- `CF-Ray`: `87523eb2aa012d28-IAD`
- `User-Agent`: `BTMuli/BangumiToday 0.1.0.1 (https://github.com/BTMuli/BangumiToday)`

**Comment by trim21** [comment]
确实

**Comment by trim21** [comment]
试试，应该好了

**Comment by BTMuli** [comment]
确实好了，感谢。
