### ISSUE TITLE
[BUG]: 条目搜索参数缺失

### ISSUE THREAD

**Issue by BTMuli** [bangumi/server#532]
**描述**

在 [开放API文档](https://bangumi.github.io/api/#/%E6%9D%A1%E7%9B%AE/searchSubjects) 的条目搜索 `v0/search/subjects` 中，其返回类型包含 `limit` `offset` `total` 等标识返回数据限制、偏移、总数的字段。

但是在请求参数的 `schema` 中并未看到诸如 `limit` `offset` 等标明偏移量的字段说明

且参考类似接口（比如[获取条目章节](https://bangumi.github.io/api/#/%E6%94%B6%E8%97%8F/patchUserSubjectEpisodeCollection)），在字段中添加 `limit` `offset`等字段，经过测试均无效

**如何重现**

1. 请求 [搜索条目](https://bangumi.github.io/api/#/%E6%9D%A1%E7%9B%AE/searchSubjects) 接口
2. 尝试设定 `limit` `offset` 字段

**预期**

添加 `offset` `limit` 字段支持

**实际行为**

略

**额外信息**

略

**Comment by BTMuli** [comment]
另：设定排序规则返回结果似乎没有变化。
请求参数：`{"keyword":"测试","sort":"rank","filter":{"type":[2],"nsfw":false}}`

**Comment by trim21** [comment]
欢迎PR（

**Comment by BTMuli** [comment]
是我的问题，`POST` 请求的 `data` 与 `param` 是分开的，`param` 里面放 `{"limit":10,"offset":20}`是有效的
