### ISSUE TITLE
[BUG]: non-printable characters in API response

### ISSUE THREAD

**Issue by EverettSummer** [bangumi/server#533]
**描述**
https://bgm.tv/subject/137133
网页上看起来正常，但API包含非可打印字符。
简短的表述你遇到的问题
![image](https://github.com/bangumi/server/assets/55684557/9d90774a-e32b-4db6-ab2b-72e9d30bf7a2)

**如何重现**

1. ...

**预期**

**实际行为**

**额外信息**

- `CF-Ray`: ``
- `User-Agent`: ``

**Comment by trim21** [comment]
原本wiki内容就这样

**Comment by trim21** [comment]
感觉不算本仓库的bug...

**Comment by EverettSummer** [comment]
放到这里的原因是认为这个unicode是怎么进入库的。是不是缺乏sanitize

**Comment by trim21** [comment]
直接就没过滤（

**Comment by trim21** [comment]
写入数据库是主站负责的
