### ISSUE TITLE
关于 grid 大小的 image

### ISSUE THREAD

**Issue by everpcpc** [bangumi/server#560]
目前看起来是 large 直接 scale 出来的，这个 URL 格式是什么背景呢？
```
Grid:   "https://lain.bgm.tv/r/100/pic/cover/l/" + s,
```

主要问题是对于 character 和 person 的 grid image，默认的是维基人手动切过的图，例如
https://lain.bgm.tv/pic/crt/g/91/e0/90739_crt_CBNB7.jpg
跟 large scale 出来还是不一样的，现在没有方式能拿到这个头像。

**Comment by trim21** [comment]
https://github.com/bangumi/img-proxy

**Comment by trim21** [comment]
对哦，角色/人物图是维基人手动切的
