### ISSUE TITLE
[Feature Request]: 条目排名列表 API

### ISSUE THREAD

**Issue by everpcpc** [bangumi/server#563]
**你想添加的新功能**

* 按排名顺序返回的条目列表
* 按年份[月份]返回的条目列表

**Tracking**

- #564

**Comment by trim21** [comment]
![image](https://github.com/bangumi/server/assets/13553903/c8de852a-dc65-4790-9ec1-05f6ccb4007a)
(

**Comment by trim21** [comment]
有哪个bot可以实现这个吗（

**Comment by everpcpc** [comment]
看了一圈感觉大家的 bot 都不怎么维护了，不如自己写个 action 处理，反正操作也很简单 TAT

**Comment by trim21** [comment]
不如手动处理算了
