### ISSUE TITLE
[Bug] Bangumi API timeout

### ISSUE THREAD

**Issue by Predidit** [bangumi/server#642]
似乎所有的v0 API都不再返回数据，看上去好像宕机了

eg: https://api.bgm.tv/v0/subjects/265391

大佬能帮忙看一下吗

**Comment by Predidit** [comment]
@trim21 

好像又寄了

**Comment by Predidit** [comment]
也许在解决问题之前, 我们可以尝试通过外部探针来触发服务重启？

**Comment by trim21** [comment]
理论上是可以在服务死了的时候就重启进程，但是这样的话我就没法 debug 了

**Comment by trim21** [comment]
我现在不确定是为什么会出现这个问题，所以需要线上出现问题的时候我 attach 进去 debug...

**Comment by Predidit** [comment]
之前我写 golang web 的时候，遇到的宕机基本都是 orm 维护的数据库连接池出了问题，大佬关注过这方面没有呢。

**Comment by trim21** [comment]
多开了个实例作为 fallback ， 下次应该不会直接爆炸了。

感觉不是数据库链接的问题，现在是 net/http 直接把连tcp链接给 reset 掉了

**Comment by Predidit** [comment]
理论上数据库连接出现阻塞的时候，客户端的请求会抛出错误，然后 net/http 会立即 reset 掉失败的连接

我们之前遇到的问题，一个不常用的 API 服务创建的数据库连接因为一些意外并不会销毁，然后达到 orm 设定的连接数上限，阻塞掉此实例上的所有数据库操作。由于数据库的连接数上限远大于单个示例的连接数上限，其他实例可以正常工作。

我不清楚 bangumi server 的实现, 只是猜测一下

**Comment by trim21** [comment]
curl /metrics 也被 reset 了， 没数据库请求的路由也会受影响吗

**Comment by trim21** [comment]
修复了个race问题，再观察一下（）

**Comment by Predidit** [comment]
> curl /metrics 也被 reset 了， 没数据库请求的路由也会受影响吗

啊，那应该不是这个问题，打扰您了

**Comment by trim21** [comment]
怀疑是我写的 github.com/trim21/go-phpserialize 里面有 data race，出错之前最后的 log 的位置也能对的上。

**Comment by trim21** [comment]
好像还真是 database/sql 的连接池出了问题，有上万个 goroutines 在 sql.DB.conn 的 select 上面等待。 

可能是因为我不小心用了 context.Background 的原因

**Comment by trim21** [comment]
感觉修好了，先关issue了
