### ISSUE TITLE
获取条目讨论

### ISSUE THREAD

**Issue by Jarvie8176** [bangumi/server#67]
https://github.com/bangumi/server/issues/53

# Endpoint

- [ ] `GET /v0/subjects/:subjectId/topics` 获取条目下全部讨论
- [ ] `GET /v0/subjects-topics/:topicId` 获取条目讨论内容

# Authz

- [ ] 讨论查看权限
- [ ] 回复查看权限

**Comment by Trim21** [comment]
第二个API可能会有问题，小组讨论的id和条目讨论的id有可能相同

**Comment by Jarvie8176** [comment]
改成了`GET /v0/subjects/topics/:topicId`但是router可能会撞，测试一下

**Comment by Trim21** [comment]
`/subjects_topics/`或者什么的吧，这样跟原有路由冲突了

**Comment by Jarvie8176** [comment]
ok，改成了`/v0/subjects-topics/:topicId`

https://stackoverflow.com/questions/10302179/hyphen-underscore-or-camelcase-as-word-delimiter-in-uris

**Comment by Sai** [comment]
这个 router 不支持正则匹配吗？

支持的话就 
/v0/subjects/topics/:topic_id

不支持就
/v0/subjects/:subject_id/topics/:topic_id

**Comment by Trim21** [comment]
> /v0/subjects/:subject_id/topics/:topic_id

`topic_id` 本来就是全局ID，第二个没必要吧。

**Comment by Sai** [comment]
subjects-topics 这样少了一层 namespace，看起来不太舒服。

**Comment by Trim21** [comment]
还是带subject id更合适一点，这样发帖API是 POST `/v0/subjects/:subject_id/topics`

**Comment by Trim21** [comment]
https://cloud.google.com/apis/design/design_patterns#get_unique_resource_from_sub-collection 或者参照这个，用 `/v0/subjects/-/topics/:topicId`
