### ISSUE TITLE
是否可以更新下 pkg/vars 下的常量对应关系的 json 文件

### ISSUE THREAD

**Issue by Livinfly** [bangumi/server#688]
在使用 Archive 数据的时候，发现 `subject_id = 11` 时，实际有 `type = 1` 且 `platform = 1006` 而 json 文件中没有对应的常量。
点开网站后发现实际是有对应是 「公式书」，所以怀疑常量对应 json 文件不是最新的，希望可以有更新，目前只发现 platform 剩下两个的常量对应 json 文件还不确定是不是最新的。

**Comment by trim21** [comment]
应该要换到 https://github.com/bangumi/common 这个仓库里的新yaml的

**Comment by Livinfly** [comment]
> 应该要换到 https://github.com/bangumi/common 这个仓库里的新yaml的

好的，方便的话可以在 README 加个最新版本的指路，十分感谢！

**Comment by trim21** [comment]
我现在才明白你是需要这个新的列表而不是需要更新api（

**Comment by Livinfly** [comment]
> 我现在才明白你是需要这个新的列表而不是需要更新api（

在用存档的静态数据搞东西来着（（
