### ISSUE TITLE
[Feature Request]: /v0/user/me是否能支持查询email和regdate

### ISSUE THREAD

**Issue by xrz-cloud** [bangumi/server#689]
**你想添加的新功能**
如题

**你希望的解决方案**
- 当使用bgm作为 oauth2 provider 时，email字段可以便于关联其它账户。
- 根据regdate注册日期可以限制一些数据/功能的显示（如nsfw）。

**其他可能的替代方案**

**其他相关信息**

**Comment by trim21** [comment]
能PR吗？

**Comment by xrz-cloud** [comment]
周末才有空，到时候做做看
