### ISSUE TITLE
[Feature Request]: 提供条目筛选搜索

### ISSUE THREAD

**Issue by KiedaTamashi** [bangumi/server#79]
- [ ] 希望能够增加条目的筛选搜索，简单的比如年份/类别/tag的筛选。

目前这个搜索功能感觉有点弱。

之前没有用python写过后端，底层数据库用的是mysql么？方便后续做复杂查询吗？

**Comment by Sai** [comment]
https://github.com/bangumi/search/issues/1

**Comment by Trim21** [comment]
在做了
