### ISSUE TITLE
relicense AGPL

### ISSUE THREAD

**Issue by Trim21** [bangumi/server#87]
@Sai 老板建议改成 AGPL 授权，目前代码库包括我共有6个 contributors。由于agpl和bsd并不相容，所以希望能征得大家的同意，一次性修改掉，避免复杂的问题。

- [x] @Jarvie8176 
- [x] @Sociosarbis
- [ ]  @MoguCloud
- [x]  @AspectLeft
- [x]  @MichaelMai2000 

希望mogucloud看到这个issue回复一下，emoji没有通知提醒…

**Comment by Sociosarbis** [comment]
同意

**Comment by MoguCloud** [comment]
同意
