### ISSUE TITLE
[feature request] subject请求请带上nsfw字段

### ISSUE THREAD

**Issue by ekibun** [bangumi/server#9]
隔壁客户端经常被谷歌商店下架（bgm38）

subject列表请求也需要带上过滤或者标记，类似于

```
api.bgm.tv/subject/search?key=xxx&filter=nsfw,eq,0
```

最好是小组和讨论也能带上

**Comment by Trim21** [comment]
> 隔壁客户端经常被谷歌商店下架（bgm38）

google play store 下架是个啥政策...
