### ISSUE TITLE
[Feature Request]: 目录

### ISSUE THREAD

**Issue by Trim21** [bangumi/server#98]
大概的路由

GET `/v0/indices/{index_id}`

GET `/v0/indices/{index_id}/subjects`

支持 `type` 参数进行条目类型筛选，应该支持分页。

GET `/v0/indices/{index_id}/comments` （这个参照帖子详情的响应）

如果包含任何一个 NSFW 条目，本目录应该被认为是 NSFW 目录，不允许没有 NSFW 条目查看权限的人查看目录，返回HTTP 404。

SQL 表这里 https://github.com/bangumi/dev-env/blob/master/un-processed/bangumi_index%20(2).sql

**Comment by Sociosarbis** [comment]
1. `/v0/indices`不需要目录列表的接口吗？
2. 目录的`nsfw`值是否需要获取它收录的所有条目才能判断，还是`chii_index`的`ban`字段就表明`nsfw`了？
3. 如果是`nsfw`，那么以`/v0/indices/{index_id}`前缀的接口都应该返回`404`？

**Comment by Trim21** [comment]
1. 先不做 `/v0/indices` 了吧。
2. 这个 `chii_index`.`ban` 得问下 @Sai
3. 对

**Comment by Sai** [comment]
2. ban > 0 只是表示自己/封禁删除了，nsfw 是根据内部条目判断的
